version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: todo
    volumes:
      - ./db/.data:/var/lib/postgresql/data
    ports:
      - "5433:5432"